### ISSUE TITLE
Average block time is always null and so is not appearing in UI

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/dotstats#23]
If I run a node and its generating blocks, it sends `message.payload` to the front-end in https://github.com/polkadot-js/dotstats/blob/master/packages/frontend/src/Connection.ts#L102, but in `BestBlock` the `message.payload` is `[820468, 1532502970369, null]`, where the last element in the array is the `averageBlockTime` that's sent from the backend in https://github.com/polkadot-js/dotstats/blob/master/packages/backend/src/Chain.ts#L59, whose default value is `null`. Should it be changing?

**Comment by maciejhirsz** [comment]
This is working as intended if you have a node that isn't syncing or producing blocks (stuck at the same block).
