### ISSUE TITLE
Click to copy validator address

### ISSUE THREAD

**Issue by maciejhirsz** [polkadot-js/dotstats#41]
Bonus points for a tooltip view that's nicer than using the default `title` on-hovers.

**Comment by ltfschoen** [comment]
Where does it currently show the address of a node?

This is how we implemented copy to clipboard in polkadot-js/apps: https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/CopyButton.tsx

**Comment by maciejhirsz** [comment]
On the list node, you need recent substrate though (and to run the node as a `--validator`).

**Comment by ltfschoen** [comment]
It's showing validators in BBQ Birchwhen the validator column is activated

**Comment by maciejhirsz** [comment]
Done in #82.
