### ISSUE TITLE
Calculate average block time

### ISSUE THREAD

**Issue by maciejhirsz** [polkadot-js/dotstats#9]

**Comment by ltfschoen** [comment]
It appears as though the functionality of calculating the average block time already been implemented. Although there is duplication:
* https://github.com/polkadot-js/dotstats/blob/master/packages/backend/src/Node.ts#L180
* https://github.com/polkadot-js/dotstats/blob/master/packages/backend/src/Chain.ts#L112

The average blocktime is updated in the frontend here:
* https://github.com/polkadot-js/dotstats/blob/master/packages/frontend/src/Connection.ts#L123
* https://github.com/polkadot-js/dotstats/blob/master/packages/frontend/src/state.ts#L8
* https://github.com/polkadot-js/dotstats/blob/master/packages/frontend/src/components/Chain.tsx#L86

**Comment by maciejhirsz** [comment]
Ye, the average block time on Node isn't being used right now (it's not displayed anywhere). Note that average block time for node can be different than that of the chain as a whole (which is getting block times from different nodes, whichever is fastest at any given block height).
